CREATE TABLE budget_items (
    id SERIAL PRIMARY KEY,
    item_group_id INT NOT NULL,
    name VARCHAR NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    fund BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR,
    favorite BOOLEAN NOT NULL DEFAULT FALSE
)
