[package]
name = "budgie"
version = "0.1.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["v4"] }
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15.0"
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["diesel_postgres_pool"] }
r2d2-diesel = "1.0"
r2d2 = "0.8"
